language: php
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'

install:
- composer install --no-interaction
- composer require --no-interaction  mikk150/yii2-sms ^1.0

script:
- vendor/bin/phpcs --standard=vendor/yiisoft/yii2-coding-standards/Yii2 --extensions=php src
- php vendor/bin/codecept run --coverage --coverage-xml

after_success:
- bash <(curl -s https://codecov.io/bash)
